DROP DATABASE IF EXISTS csfd;
CREATE DATABASE csfd WITH TEMPLATE template0;
DROP USER IF EXISTS csfd;
CREATE USER csfd WITH PASSWORD 'csfd';
ALTER USER csfd CREATEDB;
GRANT ALL PRIVILEGES ON DATABASE csfd to csfd;
\c csfd;
CREATE EXTENSION IF NOT EXISTS unaccent CASCADE;
