# Generated by Django 2.2.28 on 2025-05-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_normalized', models.CharField(db_index=True, max_length=100)),
                ('external_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_normalized', models.CharField(db_index=True, max_length=100)),
                ('external_id', models.IntegerField(unique=True)),
                ('actors', models.ManyToManyField(related_name='films', to='top_favourites.Actor')),
            ],
        ),
    ]
